### ISSUE TITLE
Sankey Visualization is not displayed properly

### ISSUE THREAD

**Issue by bayusky** [netsage-project/netsage-sankey-panel#25]
Sankey version : 1.1.1  
Grafana version : 10.4.2 
OS : Debian 11

My issue is all value stacked on top of each other
![image](https://github.com/netsage-project/netsage-sankey-panel/assets/14219628/aa7a94ea-722b-4934-adc0-2b5c75654aea)

The table view is like this :
![image](https://github.com/netsage-project/netsage-sankey-panel/assets/14219628/035e1d55-0357-4096-afbf-204b82a1c58b)

Install via grafana-cli
![image](https://github.com/netsage-project/netsage-sankey-panel/assets/14219628/35412ac3-55da-4f63-a042-a17e0fd73f3e)

How to fix this?

**Comment by pragma-** [comment]
I'm having the same issue. I'm also on Grafana 10.4.2 using netsage-sankey-panel 1.1.1. I saw this plugin in a video and I was excited to try it out. But does not seem to be working in Grafana 10.4.2.

@KatrinaTurner Please look at this issue.

**Comment by KatrinaTurner** [comment]
Hey guys. Sorry, I'm a bit behind and still on 10.4.0
I will put this on my to do list next week to check out 10.4.2. 

@bayusky your problem may also be that since all the counts are 0, it has no width to use for the nodes. Can you try with a different metric?

**Comment by pragma-** [comment]
@KatrinaTurner Thanks for the quick response! In my case I do have counts but there are no lines rendered:

Table:
![](https://i.imgur.com/XoWjzYc.png)

Panel:
![](https://i.imgur.com/ouqR0ji.png)

**Comment by pragma-** [comment]
@KatrinaTurner I've been playing around with the panel. I've made some interesting discoveries. If I drag resize the panel really small, the lines start drawing at the exact point when the labels invert past each other:
![](https://i.imgur.com/pjjUO1Y.png)
The lines also appear if I drag resize the panel to be very, very large. In both cases, small and large, the pop-up text when you mouseover a line renders behind the panel instead of on top of it.

**Comment by pragma-** [comment]
By "very, very" large I mean 2 or 3 pages tall. I have to click the bottom right corner and then drag down past the bottom edge of the browser window while simultaneously dragging it left and right to cause the scrollbar to keep doing down until lines finally start appearing in the panel after about 2 and half pages of scrolling.

**Comment by pragma-** [comment]
Experimenting some more. It turns out I need to keep drag resizing it taller and taller for more and more lines to draw in. I have to make the panel about 6 pages tall to see all the lines. At this height it's quite difficult to trace the lines from the left side to the right side. Hopefully this can be adjusted to render properly at a sensible height.

**Comment by bayusky** [comment]
@KatrinaTurner Oh I see, I was able to see visualization when the data are coming in and minimum count are 1 not 0. Thanks for the feedback and sorry for late reply.

**Comment by KatrinaTurner** [comment]
@pragma- I would suggest decreasing your "Node Padding" option.  This will allow the nodes to be closer together, and you'll be able to fit more in the panel without it being so tall.
That being said, this plugin isn't designed to use with super large data sets because as you pointed out, it gets too hard to trace if you're having to go down multiple pages.  If your data is mostly like the table you showed and just has a source and dest, you can also try out the netsage-slopegraph-panel.  It uses color instead of line width to denote value, so is a little better for larger data sets. 
Hope this helps!

**Comment by bayusky** [comment]
@KatrinaTurner interesting, definitely will try slopegraph.

**Comment by pragma-** [comment]
Thank you for the suggestions. I will experiment with the node padding option soon.

However, even with a small data set the graph doesn't render until I resize it to very small or very large. When it's resized to small enough to flip the labels across the Y axis the lines immediately render.

Additionally, the label/counter that appears on mouse hover render behind/under the panel.

**Comment by KatrinaTurner** [comment]
I believe the node padding should help substantially in this area. I've
started checking it in 10.4.2 and it behaves similarly to previous versions
of Grafana. It is just a larger viz in general, we usually use it with at
least half screen height.
I do know about the tooltip rendering incorrectly and will be submitting
that fix this week. Thank you!

**Comment by pragma-** [comment]
The node padding indeed resolves my issue. Lines are now being rendered with a node padding of 1. Thank you!

**Comment by KatrinaTurner** [comment]
Ah, then yes, sankey is definitely going to be better than the slope
graph.  This is looking good though!  I actually just submitted another
update to Grafana to allow the label sizes to be changed (a FR from someone
else).
Once v1.1.3 is available, this option will be available to you and may be
helpful here.

*Katrina Turner*
*Data Visualization & User Interface Developer*
Energy Sciences Network (ESnet)

Lawrence Berkeley National Laboratory
